// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPekara.Models;

namespace WebPekara.Migrations
{
    [DbContext(typeof(PekaraContext))]
    partial class PekaraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebPekara.Models.Kasa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Novac")
                        .HasColumnType("int")
                        .HasColumnName("Novac");

                    b.Property<int>("Racun")
                        .HasColumnType("int")
                        .HasColumnName("Racun");

                    b.HasKey("ID");

                    b.ToTable("Kasica");
                });

            modelBuilder.Entity("WebPekara.Models.Pecivo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnType("int")
                        .HasColumnName("Cena");

                    b.Property<int>("Gramaza")
                        .HasMaxLength(255)
                        .HasColumnType("int")
                        .HasColumnName("Gramaza");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int")
                        .HasColumnName("Kolicina");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.Property<int?>("StanjeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StanjeID");

                    b.ToTable("Peciva");
                });

            modelBuilder.Entity("WebPekara.Models.Radnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.Property<int>("Jmbg")
                        .HasColumnType("int")
                        .HasColumnName("Jmbg");

                    b.Property<string>("Pozicija")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Pozicija");

                    b.Property<string>("Prezime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Prezime");

                    b.Property<int?>("RadnjaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RadnjaID");

                    b.ToTable("Radnik");
                });

            modelBuilder.Entity("WebPekara.Models.Radnja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Radnja");
                });

            modelBuilder.Entity("WebPekara.Models.Stanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KasaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KasaID");

                    b.ToTable("Stanje");
                });

            modelBuilder.Entity("WebPekara.Models.Pecivo", b =>
                {
                    b.HasOne("WebPekara.Models.Stanje", "Stanje")
                        .WithMany("nizPeciva")
                        .HasForeignKey("StanjeID");

                    b.Navigation("Stanje");
                });

            modelBuilder.Entity("WebPekara.Models.Radnik", b =>
                {
                    b.HasOne("WebPekara.Models.Radnja", "Radnja")
                        .WithMany("NizRadnika")
                        .HasForeignKey("RadnjaID");

                    b.Navigation("Radnja");
                });

            modelBuilder.Entity("WebPekara.Models.Stanje", b =>
                {
                    b.HasOne("WebPekara.Models.Kasa", "Kasa")
                        .WithMany("Stanje")
                        .HasForeignKey("KasaID");

                    b.Navigation("Kasa");
                });

            modelBuilder.Entity("WebPekara.Models.Kasa", b =>
                {
                    b.Navigation("Stanje");
                });

            modelBuilder.Entity("WebPekara.Models.Radnja", b =>
                {
                    b.Navigation("NizRadnika");
                });

            modelBuilder.Entity("WebPekara.Models.Stanje", b =>
                {
                    b.Navigation("nizPeciva");
                });
#pragma warning restore 612, 618
        }
    }
}
